/* URDME model file, automatically generated by pyURDME. */
#include <stdlib.h>
#include <math.h>
#include "propensities.h"
#include <stdio.h>

/* Species names */
#define A x[0]


/* Number of reactions */
#define NR 0



/* Reaction definitions */


PropensityFun *ALLOC_propensities(void)
{
    PropensityFun *ptr = (PropensityFun *)malloc(sizeof(PropensityFun)*NR);
    

    return ptr;
}

void FREE_propensities(PropensityFun* ptr)
{
    free(ptr);
}

