/* URDME model file, automatically generated by pyURDME. */
#include <stdlib.h>
#include <math.h>
#include "reactions.h"
#include "species.h"

int number_of_reactions(void)
{
	return __NUMBER_OF_REACTIONS__;
}

int number_of_species(void)
{
	return __NUMBER_OF_SPECIES__;
}

species **initialize_species(void)
{
	species **ptr = (species **)malloc(sizeof(species *)*number_of_species());
	
    __DEFINE_SPECIES__
    
	return ptr;
}

reaction **initialize_reactions(void)
{
	reaction **ptr = (reaction **)malloc(sizeof(reaction *)*number_of_reactions());
	
	__DEFINE_REACTIONS__
    
	return ptr;
}
