/* URDME model file, automatically generated by pyURDME. */
#include <stdlib.h>
#include <math.h>
#include "propensities.h"
#include <stdio.h>

/* Species names */
__DEFINE_SPECIES__

/* Number of reactions */
#define NR __NUMBER_OF_REACTIONS__

__DEFINE_PARAMETERS__

/* Reaction definitions */
__DEFINE_REACTIONS__

PropensityFun *ALLOC_propensities(void)
{
    PropensityFun *ptr = (PropensityFun *)malloc(sizeof(PropensityFun)*NR);
    
__DEFINE_PROPFUNS__
    return ptr;
}

void FREE_propensities(PropensityFun* ptr)
{
    free(ptr);
}

