/* URDME model file, automatically generated by pyURDME. */
#include <stdlib.h>
#include <math.h>
#include "propensities.h"
#include <stdio.h>

/* Species names */
#define MinD_m x[0]
#define MinD_c_atp x[1]
#define MinD_c_adp x[2]
#define MinD_e x[3]
#define MinDE x[4]


/* Number of reactions */
#define NR 6

const double sigma_d = 2.5e-08;
const double sigma_dD = 1.6e-21;
const double sigma_e = 9.3e-20;
const double sigma_de = 0.7;
const double sigma_dt = 1.0;


/* Reaction definitions */
double R1(const int *x, double t, const double vol, const double *data, int sd)
{
    return sigma_d*MinD_c_atp;
}

double R2(const int *x, double t, const double vol, const double *data, int sd)
{
    return sigma_dD*MinD_c_atp*MinD_m;
}

double R3(const int *x, double t, const double vol, const double *data, int sd)
{
    return sigma_e*MinD_e*MinD_m;
}

double R4(const int *x, double t, const double vol, const double *data, int sd)
{
    return sigma_de*MinDE*MinD_e;
}

double R5(const int *x, double t, const double vol, const double *data, int sd)
{
    return sigma_dt*MinD_c_adp;
}

double R6(const int *x, double t, const double vol, const double *data, int sd)
{
    return sigma_dD*MinDE*MinD_c_atp;
}



PropensityFun *ALLOC_propensities(void)
{
    PropensityFun *ptr = (PropensityFun *)malloc(sizeof(PropensityFun)*NR);
    
    ptr[0] = R1;
    ptr[1] = R2;
    ptr[2] = R3;
    ptr[3] = R4;
    ptr[4] = R5;
    ptr[5] = R6;

    return ptr;
}

void FREE_propensities(PropensityFun* ptr)
{
    free(ptr);
}

